### PR TITLE
Fix label marshalling

### PR DESCRIPTION
**Pull request by svanharmelen**

### CODE REVIEW

**Comment by svanharmelen** [comment]
@matm I didn't have time to test all use cases, so please let me know if this PR properly fixes the `label` issue. It should as far as I can tell and IMO this is a more generic and clean solution...

**Comment by matm** [comment]
Thanks for your quickc action. Should do the job indeed. Are we sure only labels are concerned? I mean no other list fields in GitLab's API doc that would require a custom marshaling action?

**Comment by svanharmelen** [comment]
A first scan only shows the labels field. But if other pop up, the fix could be generalized by renaming `type Labels` to a more generic name and use it for the other fields as well. But for now I didn't spot them...

**Comment by matm** [comment]
Okay, should be fine. I'll test it today. Thanks.

**Pull request merged**
