### PR TITLE
Adding GitPod support

### LINKED ISSUE #1422: Add gitpod support to be able to open up a preconfigured development workspace for this library
Recently the downstream [GitLab Terraform Provider](https://github.com/gitlabhq/terraform-provider-gitlab) repository added support for opening up a preconfigured workspace for development work in GitPods.  This has greatly increased the productivity of some of the development as local machines only need a compatible web browser & a GitPod account to utilize a preconfigured GitPod environment.

Downstream PR's with the additions needed for GitPod support
- https://github.com/gitlabhq/terraform-provider-gitlab/commit/47d8c3f6322a18d716203d57f1a3b56a8ba63e39
- https://github.com/gitlabhq/terraform-provider-gitlab/commit/52afe3c084a54930295e18dd5764018c2fd53976

### PR DESCRIPTION
**Pull request by Shocktrooper**
Resolves #1422

### CODE REVIEW

**Comment by Shocktrooper** [comment]
@svanharmelen Ready for review when you have time

**Comment by svanharmelen** [comment]
How (if at all) does this related to #1392? Of is this _only_ used for development where the solution in #1392 is _only_ used for acceptance tests?

Just trying to understand if we need both these approaches for this package...

**Comment by Shocktrooper** [comment]
@svanharmelen I would say yes both are good and work in conjunction with each other vs one being a replacement for the other. This is used for development but you can also run the acceptance tests in a GitPod if you desire.  The only duplication that currently exists between the 2 PR's are the container startup scripts and either PR can go first as they should be basically identical.

**Comment by Shocktrooper** [comment]
@svanharmelen We can merge this and it will be combined and coincide with the work done on #1392

**Comment by svanharmelen** [comment]
I'm going to wait with this one until I heart back from GitLab (I am talking with them about this repo)...

**Comment by Shocktrooper** [comment]
@svanharmelen Is that true of all pull requests on this repo or just ones pertaining to ease of development?

**Comment by svanharmelen** [comment]
@Shocktrooper as you probably already noticed, it's only true for PRs that introduce new "concepts". PRs that contain bugfixes or that add missing or new APIs will still be reviewed and merged.

And once I have more clarity about the future of this repo, I (or someone else) will have a look at these ones as well!

**Comment by RicePatrick** [comment]
I'll go ahead and close this since it's old and has conflicts at this point. We'll likely add something to it post-migration once we've figured that out 😄

**Pull request closed without merging**
