### PR TITLE
Add References to MergeRequest.

### PR DESCRIPTION
**Pull request by finn-ball**
Adds references as defined in the API:

```
    "references": {
      "short": "!1",
      "relative": "my-group/my-project!1",
      "full": "my-group/my-project!1"
    },
```

https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr

### CODE REVIEW

**Review by svanharmelen — APPROVED** [review]
Thanks @finn-ball!

**Comment by svanharmelen** [comment]
@finn-ball guess you need to fixup the tests first...

**Comment by finn-ball** [comment]
@svanharmelen Updated the tests. Should be ready to go now :)

**Comment by svanharmelen** [comment]
Thanks 👍🏻

**Pull request merged**
