### PR TITLE
Use Go's OAuth2 package

### PR DESCRIPTION
**Pull request by jayschwa**

### CODE REVIEW

**Comment by svanharmelen** [comment]
I'm unable to test this myself right now, but this looks really nice (and a lot better then my previous poke at this)! Didn't know there was a standard package for this, so thanks al lot @jayschwa!

Can you confirm you (properly) tested this yourself? If so, I'm good with merging this one and adding a new tag so we can properly support this auth method.

**Comment by jayschwa** [comment]
I am in the process of integrating and testing this with job's code base now. I will write back when I am finished.

**Comment by svanharmelen** [comment]
Cool, thanks!

**Comment by svanharmelen** [comment]
Cool! Thanks again @jayschwa!

**Comment by jayschwa** [comment]
Of course. I will await its inclusion in a tagged release :smiley:

**Comment by svanharmelen** [comment]
Merged into master and tagged as v0.10.3

**Pull request merged**
