### PR TITLE
Change pipeline coverage to be float64.

### PR DESCRIPTION
**Pull request by Nighthawk22**
Based on the recent change on GitLab.com https://gitlab.com/gitlab-org/gitlab/-/merge_requests/75329

### CODE REVIEW

**Comment by Ravlen** [comment]
@Nighthawk22 Hey, turns out this was not intentional, it was a bug, and it should hopefully be resolved with https://gitlab.com/gitlab-org/gitlab/-/merge_requests/76299

**Comment by svanharmelen** [comment]
Thanks for the update @Ravlen, in that case I will close this PR again. If things turn out differently, feel free to reopen it again.

**Comment by Nighthawk22** [comment]
Wow thanks for checking that back. We just experienced it in one of our services that rely on webhooks.

**Comment by caalberts** [comment]
@Nighthawk22 @svanharmelen Hi, the regression fix has been deployed and it is back to string. You could see an example here https://gitlab.com/api/v4/projects/278964/pipelines/425710966.

**Pull request closed without merging**
