### PR TITLE
Extend CommitsService (create commits / cherry-pick)

### PR DESCRIPTION
**Pull request by sindrepm**
This PR extends the `CommitsService` to also allow creating new commits and cherry-picking a commit.

See:
https://docs.gitlab.com/ce/api/commits.html#create-a-commit-with-multiple-files-and-actions
https://docs.gitlab.com/ce/api/commits.html#cherry-pick-a-commit

Also added some missing fields to the `Commit` struct.

### CODE REVIEW

**Comment by sindrepm** [comment]
@svanharmelen Can you please consider this PR? It adds the missing features from the commits API.

**Comment by svanharmelen** [comment]
@sindrepm I'll have a look at this PR early this week!

**Comment by sindrepm** [comment]
@svanharmelen Just a friendly reminder...

**Comment by svanharmelen** [comment]
I didn't forget... Just having a crazy week. But the week is not past yet 😉

**Comment by svanharmelen** [comment]
So the week passed :( But I'll merge this one right now and make just a minor tweak to keep things consistent. Will let you know when that's in so you can see the changes...

**Comment by svanharmelen** [comment]
See #140 Just a little reordering and a small change in the option structs. Thanks again for your work! Much appreciated 👍

**Pull request merged**
