### PR TITLE
Correct Json marshaling for labels of issues

### PR DESCRIPTION
**Pull request by tkschmidt**
Labels for issues should be marshalled to a list of strings instead of single (comma-seperated) string. This is according to https://docs.gitlab.com/ee/api/issues.html (22-11-2023)

### CODE REVIEW

**Review by svanharmelen — APPROVED** [review]
While more involved and backwards incompatible, I think this is the only "correct" solution for this one...

**Comment by aaronjheng** [comment]
Why was `Description` field from `CreateMergeRequestOptions` changed to `*LabelOptions`?

**Comment by svanharmelen** [comment]
Thats a mistake... Thanks for spotting it, will change it in a bit!

**Comment by svanharmelen** [comment]
Fixed in `v0.95.1`

**Pull request merged**
