### PR TITLE
fix: Only use ListOptions

### LINKED ISSUE #1625: Bug: `ListGroupRegistryRepositories` uses `ListRegistryRepositoriesOptions`
The `ListGroupRegistryRepositories` call accepts a `ListRegistryRepositoriesOptions` object as option. The problem is that `Tags` and `TagsCount` is not a valid option for `ListGroupRegistryRepositories`, only for `ListRegistryRepositoryTags`

See https://docs.gitlab.com/ee/api/container_registry.html#within-a-group (It got removed with gitlab 15.0)

> [Removed](https://gitlab.com/gitlab-org/gitlab/-/issues/336912) the tags and tag_count attributes in GitLab 15.0.

The obvious solution would be to only allow `ListOptions` as a valid parameter to indicate that `tag` and `tagCount` has no impact.

EDIT: As the initial idea would make the API incompatible with older gitlab versions, we only deprecate these usage of `ListRegistryRepositoriesOptions`.

### PR DESCRIPTION
**Pull request by linkdotnet**
Fixes #1625

### CODE REVIEW

**Comment by svanharmelen** [comment]
I understand the idea, but by using this way to fix it you make this package incompatible with older GitLab version. So I prefer to add a deprecation note instead (like this: https://github.com/xanzy/go-gitlab/blob/master/runners.go#L184)

**Comment by linkdotnet** [comment]
> I understand the idea, but by using this way to fix it you make this package incompatible with older GitLab version. So I prefer to add a deprecation note instead (like this: https://github.com/xanzy/go-gitlab/blob/master/runners.go#L184)

That makes absolute sense. Thanks. I'll update the PR soon (and update the issue)

**Comment by linkdotnet** [comment]
@svanharmelen  As the object is shared by two function calls (group level as well as project level, we can only mark the parameter in `ListGroupRegistryRepositories` as deprecated/obsolete. How does that work?

**Comment by svanharmelen** [comment]
It's not pretty, but maybe make a new type `ListGroupRegistryRepositoriesOptions`... This is a bit of a nasty one, as in that case I would also like to rename the existing one to `ListProjectRegistryRepositoriesOptions`. Not sure if its all worth it as in the end both types will still have the same options.

So maybe just add that clarification to the deprecation message? So something like:

```go
// Deprecated: These options are deprecated only for ListGroupRegistryRepositories calls. (Deprecated in GitLab 15.0)
```

**Comment by linkdotnet** [comment]
> It's not pretty, but maybe make a new type `ListGroupRegistryRepositoriesOptions`... This is a bit of a nasty one, as in that case I would also like to rename the existing one to `ListProjectRegistryRepositoriesOptions`. Not sure if its all worth it as in the end both types will still have the same options.
> 
> So maybe just add that clarification to the deprecation message? So something like:
> 
> ```go
> // Deprecated: These options are deprecated only for ListGroupRegistryRepositories calls. (Deprecated in GitLab 15.0)
> ```

Added the deprecated message on top of both fields in the options.

**Review by svanharmelen — APPROVED** [review]
Thanks 👍🏻

**Pull request merged**
