### PR TITLE
Align fields for project read, create and update APIs

### PR DESCRIPTION
**Pull request by timofurrer**

### CODE REVIEW

**Review by svanharmelen — APPROVED** [review]
Thanks once again 😉

**Comment by timofurrer** [comment]
haha, these unblock quite a few things in our side, thanks a lot! Can you release? :)

**Comment by svanharmelen** [comment]
Created tag `v0.58.0`

**Comment by timofurrer** [comment]
While you are at it, could you also include:

* https://github.com/xanzy/go-gitlab/pull/1379
* https://github.com/xanzy/go-gitlab/pull/1381

**Pull request merged**
