### PR TITLE
Make all option struct fields pointers

### LINKED ISSUE #427: Cannot use UpdateIssue to remove all issue assignees
Since `UpdateIssueOptions` defines `AssigneeIDs` as a `[]int`, and marks it as `omitempty`, it is omitted from the JSON request if an empty array is passed into it. The Gitlab API docs describe the field as follows:

> The ID of the user(s) to assign the issue to. Set to 0 or provide an empty value to unassign all assignees.

Based on the current definition of `UpdateIssueOptions`, it is impossible to unassign all assignees. You cannot remove the `omitempty` item, or every call to `UpdateIssue` will remove all issue assignees. if you want to support this, I think there needs to be a separate method.

### PR DESCRIPTION
**Pull request by svanharmelen**
Fixes #427 #1292

### CODE REVIEW

**Comment by mitar** [comment]
If we are doing this breaking change, could we also make sure to get rid of all `[]*Struct` and convert them into `[]Struct`? For example:

```go
type ReleaseAssets struct {
	Links []*ReleaseAssetLink `url:"links" json:"links"`
}
```

There is no point in having `*` there. Does API even survive sending a `null` inside the JSON array?

**Comment by svanharmelen** [comment]
`There is no point in having * there` that depends of how and where your use the items from the slice I guess. But regardless, I guess we can have a look to also update that as over time I also came to the same conclusion.

`Does API even survive sending a null inside the JSON array?` This struct is not mean to be send to the API, but I see it actually is, so that's another issue on itself 😏

**Comment by mitar** [comment]
When do you plan to merge this?

**Comment by svanharmelen** [comment]
Not sure yet... But certainly before the end of 2021, so in the coming few weeks.

**Comment by mitar** [comment]
Any reason why to delay? I am using this and it works well. I think it will be just hard to maintain this branch (it already has conflicts).

**Pull request merged**
