### PR TITLE
Add fields

### PR DESCRIPTION
**Pull request by rekby**
CreateIssueOptions + field CreatedAt
UpdateIssueOptions + field UpdatedAt

### CODE REVIEW

**Comment by svanharmelen** [comment]
Thanks @rekby! One question through... I noticed there are 2 or 3 more missing params. Shouldn't those be added as well while we're at it?

**Comment by rekby** [comment]
It will not fast.
Add parameter need not only change code and add fields to struct, but some test for it.
I have not time for additional work and test now.

I think will be better when sombody add fields if them need to work. And test it on self task (as minimum).
It will be better if I add fields, but I can do typo and fields will not work.

**Comment by rekby** [comment]
I think it will be better to commit these fields and add other in other pull request - when it will need to somebody.

**Comment by svanharmelen** [comment]
Ok that's fine. I'll add them myself... Thx!

**Pull request merged**
