### PR TITLE
# 204 add support for GET /users/:user_id/projects

### PR DESCRIPTION
**Pull request by dongmx**
This PR is to add support for "GET /users/:user_id/projects"

### CODE REVIEW

**Comment by svanharmelen** [comment]
@dongmx I'll merge this as is, but there is a small issue with this code. I'll fix that in a separate commit after merging this one. Thx!

**Comment by dongmx** [comment]
I'd like to know what issue is :)

**Comment by svanharmelen** [comment]
See this commit: 7ef3a0e1bc22af568c2f332a4d6b781005531086 The main thing is that the function (according to the API docs) accepts either a user ID or a user name, where the first implementation only accepted an ID.

**Comment by dongmx** [comment]
That's my mistake. Misguided by `:user_id`. Thanks for correct it.

**Pull request merged**
