### PR TITLE
Add support for Group Protected Environments

### PR DESCRIPTION
**Pull request by beekeep**
Add support for Group Protected Environments, similar to Project Protected Environments.

https://docs.gitlab.com/ee/api/group_protected_environments.html

### CODE REVIEW

**Comment by beekeep** [comment]
@svanharmelen This is ready for your review.

**Review by svanharmelen — APPROVED** [review]
I'm not sure if copying over all structs is the best solution here (as most of them are a one-2-one match), but for now I'll take it... Thanks 👍🏻

**Comment by beekeep** [comment]
@svanharmelen Thanks for the review.  I had the initial thought of re-using the project protected environment structs, but I wasn't sure if it would be better to create structs specific to groups, in case they do change in projects.  In the future, would you prefer re-use if the structs are the same?

**Comment by svanharmelen** [comment]
I don't know... Generally I prefer to re-use structs if it makes sense, but in this case I think this is OK.

**Pull request merged**
