### PR TITLE
refactor: add support of constants for some fields

### LINKED ISSUE #1772: Add constants for fields like status, state on various types
Pipeline, Merge Request, etc have fields which are currently marked as string but as per docs would have specific values from a list. Add a constant support for easy comparison, readability and less typing support.

### PR DESCRIPTION
**Pull request by GaikwadPratik**
closes #1772

### CODE REVIEW

**Comment by svanharmelen** [comment]
I'm not sure about this one... I do like things to be typed, but I think this might be a bit too much to add and maintain if we are going this route for the whole package (which we should in order to keep things consistent) 🤔

**Comment by GaikwadPratik** [comment]
Agreed. But we have to start somewhere. I will keep this open for another week. If you think, it would be too much maintenance by then too, we can close it

**Comment by svanharmelen** [comment]
Yeah fine to keep it open for a while as I currently have very little headroom (and time) for doing project maintenance and/or to think about this one (I co-founded a company last year and things are picking up a little)...

**Comment by GaikwadPratik** [comment]
Closing this as too much efforts for maintenance

**Comment by svanharmelen** [comment]
Sorry for being a little less response lately... But I guess this is best for now 👍🏻

**Pull request closed without merging**
