### PR TITLE
Idea for managed pagination into channels for resources

### PR DESCRIPTION
**Pull request by catouc**
For some context I maintain a package that does this already inside of the company I work for. The semantics have proven pretty useful and seem to integrate well in this library so I thought upstreaming this could be useful to the wider community.

I have written up a sample implementation for the projects API but this can essentially be repeated for every paginated resource.
Ultimately we can also think about implementing [!815](https://github.com/xanzy/go-gitlab/issues/815) behind the scenes in this down the line :thinking: 

But before I go implement loads of endpoints I thought it's worth checking if this is desired to have this or if this should be a separate more specialised package?

Happy to have a discussion!

### CODE REVIEW

**Comment by catouc** [comment]
Can' t really see why the tests are failing :thinking: unless they use the ` examples`  and are unhappy.

**Comment by svanharmelen** [comment]
@catouc thanks for your PR, yet I need to think a little bit about this one. Until now this package tries to follow the GitLab API as close as possible, but this PR introduces a custom helper function that doesn't exist as a GitLab API. So I'm not sure yet if I want to open the doors for such functions...

**Comment by catouc** [comment]
I had an idea that we could put this into a sub-package called `streaming` or something? Then it's logically separated more from the core library :thinking:

**Comment by timofurrer** [comment]
@svanharmelen @catouc I've done some small experiment to make this somewhat sustainable, see https://github.com/xanzy/go-gitlab/pull/1498

**Comment by catouc** [comment]
I maintain something similar in my internal library which has a function called `getResourcePage` that basically just accepts the resource URI, that made it somewhat sustainable without generics, of course still a lot of duplication since every List call gets its own wrapper, but I'm not sure if that cost is much different from the current cost of calls :thinking: 
Overall this looks pretty neat as an idea I think. Though the interface gets a bit confusing from the user end right now I feel and if we wrap this implementation with specific calls again, how much have we gained?

But yeah the essentially benefit of this is that you can use channels because it allows you to work page by page on what you need to do, which starts to matter once you have 10k+ resources and need to do stuff across all of them.

**Comment by catouc** [comment]
One passing thought, it's probably worth looking at making the transition over to keyset pagination as smooth as possible, which does not deal with page numbers and offsets the same way.

I have a [bare bones implementation](https://github.com/catouc/gitlab-ci-crawler/blob/main/internal/gitlab/gitlab.go#L72) ([link header stuff](https://github.com/catouc/gitlab-ci-crawler/blob/main/internal/gitlab/linkheader.go)) that's been working pretty okay so far but most of the client call need to be able to call full URLs because that's what the keyset pagination `Next` headers return, thought I'd drop that here additionally while I still remember 😄

**Comment by svanharmelen** [comment]
I think I'm going for PR #1875 for adding a form of pagination support. If you think that solution can or should be changed/updated (including naming or ergonomics) than please comment on that PR so we can get to some kind of consensus before merging that one 😏

**Pull request closed without merging**
