### PR TITLE
added vulnerabilities

### PR DESCRIPTION
**Pull request by rotiv13**

### CODE REVIEW

**Comment by rotiv13** [comment]
Just seeing if it possible to get implemented the vulnerabilities for each repo.

**Comment by svanharmelen** [comment]
Made this a draft PR as you also updated the `go.mod` file to point at your own fork... Additionally (as a premature review comment) the field types of the struct should not be `interface{}`, so please make sure they are of the correct type before finishing the PR. Thanks!

**Comment by rotiv13** [comment]
> Made this a draft PR as you also updated the `go.mod` file to point at your own fork... Additionally (as a premature review comment) the field types of the struct should not be `interface{}`, so please make sure they are of the correct type before finishing the PR. Thanks!

Yep makes sense. Thank you for the comment. I am basically experimenting with this and seeing if it is possible to get the vulnerabilities of a project. I will make it better once I see that everything is ready.

**Comment by rotiv13** [comment]
@svanharmelen if you can do a review when you have some time.

**Review by svanharmelen — APPROVED** [review]
Thanks @rotiv13! Tweaked a few small things, but looks good otherwise 👍🏻

**Pull request merged**
