### PR TITLE
Add missing pagination option to couple of endpoints

### PR DESCRIPTION
**Pull request by Lorac**
I looked the up the documentation and the gitlab source code to confirm that they do support the pagination for those endpoints.

### CODE REVIEW

**Comment by Lorac** [comment]
I dissected the source code of Gitlab to check if the result they were returning was paginated. So I am 100% sure those endpoints are paginated.

**Comment by Lorac** [comment]
There is only one in there I shouldn't have implemented tho... GetCommitDiff. The options are ignored until it's implemented by gitlab.

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/17203

**Comment by svanharmelen** [comment]
I'll take this one as your doing so much already :wink: So pulling this one in together with some optimizations in PR #341

**Comment by svanharmelen** [comment]
It's in, thanks @Lorac!

**Pull request closed without merging**
