### PR TITLE
Add import/export limits for application/settings struct

### PR DESCRIPTION
**Pull request by cyd01**

### CODE REVIEW

**Review by svanharmelen — COMMENTED** [review]
I cannot find these fields in the docs, can you point me to something that shows these fields exist? Thanks!

**Comment by cyd01** [comment]
It seems the documentation for [/application/settings](https://docs.gitlab.com/ee/api/settings.html#list-of-settings-that-can-be-accessed-via-api-calls) route is not exhaustive.  
The fields I've added correspond to the UI menu **Import and export rate limits** (under `/admin/application_settings/network` page). Theses are the only *missing* fields, but they clearly appear API request:

    curl --request GET --header "PRIVATE-TOKEN:${GITLAB_TOKEN}" "${GITLAB_URL}/api/v4/application/settings"

**Comment by cyd01** [comment]
There are also informations in this [merge request](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35728).

**Review by svanharmelen — APPROVED** [review]
In that case... LGTM! Thanks 👍🏻

**Pull request merged**
