### PR TITLE
allow to update file with empty content

### PR DESCRIPTION
**Pull request by Murphylu1993**

### CODE REVIEW

**Comment by svanharmelen** [comment]
Good find @Murphylu1993! Yet the correct solution is to make the struct follow the option struct pattern used in the rest of this package. So I created #955 for that in order to solve this. Please let me know if the fix in that PR also works for you. Thanks!

**Comment by svanharmelen** [comment]
Would be nice if you can verify the solution I proposed in PR #955 so that we can merge that one. Thanks!

**Comment by Murphylu1993** [comment]
> Would be nice if you can verify the solution I proposed in PR #955 so that we can merge that one. Thanks!

sure, merge plz

**Comment by svanharmelen** [comment]
Check.. Thanks!

**Pull request closed without merging**
