### PR TITLE
support oauth token.

### PR DESCRIPTION
**Pull request by simpleelegant**

### CODE REVIEW

**Comment by simpleelegant** [comment]
I forgot to update *_test.go files. I close this pull request, and will create a new pull request.

**Comment by svanharmelen** [comment]
@simpleelegant looks great, thanks!

Just a quick premature comment... I think it would be better to create a new func `NewOAuthClient(...)` (or something like that), so we don't break all programs currently using this package.

Looking forward to the new PR... 👍

**Comment by svanharmelen** [comment]
@simpleelegant maybe something like this would be nice:

```go
func NewClient(httpClient *http.Client, token string) *Client {
	return newClient(httpClient, PrivateToken, token)
}

func NewOAuthClient(httpClient *http.Client, tokenType TokenType, token string) *Client {
	return newClient(httpClient, OAuthToken, token)
}

func newClient(httpClient *http.Client, tokenType TokenType, token string) *Client {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	c := &Client{client: httpClient, tokenType: tokenType, token: token, UserAgent: userAgent}
	if err := c.SetBaseURL(defaultBaseURL); err != nil {
		// should never happen since defaultBaseURL is our constant
		panic(err)
	}

	c.Branches = &BranchesService{client: c}
	c.Commits = &CommitsService{client: c}
	c.DeployKeys = &DeployKeysService{client: c}
	c.Groups = &GroupsService{client: c}
	c.Issues = &IssuesService{client: c}
	c.Labels = &LabelsService{client: c}
	c.MergeRequests = &MergeRequestsService{client: c}
	c.Milestones = &MilestonesService{client: c}
	c.Notes = &NotesService{client: c}
	c.Namespaces = &NamespacesService{client: c}
	c.Projects = &ProjectsService{client: c}
	c.ProjectSnippets = &ProjectSnippetsService{client: c}
	c.Repositories = &RepositoriesService{client: c}
	c.RepositoryFiles = &RepositoryFilesService{client: c}
	c.Services = &ServicesService{client: c}
	c.Session = &SessionService{client: c}
	c.Settings = &SettingsService{client: c}
	c.SystemHooks = &SystemHooksService{client: c}
	c.Users = &UsersService{client: c}

	return c
}
```

**Comment by simpleelegant** [comment]
@svanharmelen Good idea!

**Pull request closed without merging**
