### PR TITLE
feat: add support for merge results/trains

### LINKED ISSUE #1782: Add Support for Merge Results
Re-opening #1185  in another one

### PR DESCRIPTION
**Pull request by GaikwadPratik**
`Merge Result/Trains` were enabled in GitLab v12(https://docs.gitlab.com/ee/api/merge_trains.html). Adding those api in the library.

closes #1782

### CODE REVIEW

**Comment by GaikwadPratik** [comment]
@svanharmelen, Can you please review this one?

**Comment by GaikwadPratik** [comment]
@svanharmelen ,

any thoughts? I have sort if stopped development of my code til this PR is merged.

**Review by svanharmelen — APPROVED** [review]
Updated a few things, ready to be merged now. Thanks @GaikwadPratik 👍🏻

**Comment by GaikwadPratik** [comment]
Thank you.

**Pull request merged**
