### PR TITLE
Added pagination helper

### PR DESCRIPTION
**Pull request by Roemer**
Added a pretty flexible pagination helper.

It allows to abort on certain criterias and also to process the items after each page if wanted.

Open for discussion!

### CODE REVIEW

**Comment by timofurrer** [comment]
I've implemented something similar in #1498 🤔

**Comment by timofurrer** [comment]
I guess iterators would also be nice for this once they land 🤔

**Comment by Roemer** [comment]
Any feedback here? I still think this would be a good addition.

**Comment by JordanP** [comment]
There's not a lot of Gitlab specific things in there. It increases the API for something that could live outside of this package. For some reason I prefer the aesthetics of https://github.com/xanzy/go-gitlab/pull/1498 Also maybe we should wait for "official" support of Iterator in Go ?

**Comment by costela** [comment]
O somehow totally missed this PR and duplicated some of the work here: #1875
Apologies for that :sweat: 

That PR also includes initial [`rangefunc`](https://go.dev/wiki/RangefuncExperiment) support, now that iterators are a thing (albeit experimentally).

**Comment by svanharmelen** [comment]
I think I'm going for PR #1875 for adding a form of pagination support. If you think that solution can or should be changed/updated (including naming or ergonomics) than please comment on that PR so we can get to some kind of consensus before merging that one 😏

**Pull request closed without merging**
