### PR TITLE
fix(merge_requests/issues): fix Issue.ID type to handle Jira issues

### PR DESCRIPTION
**Pull request by QuentinBrosse**
This MR fixes the `Issue.ID` type field that can be an integer or a string to support third parties issue systems (like Jira).

The Gitlab documentation page is available [here](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-that-will-close-on-merge).

### CODE REVIEW

**Comment by QuentinBrosse** [comment]
Hi @svanharmelen, can you give a look at this MR, please? :)

**Comment by svanharmelen** [comment]
Sorry for the delay, will try to find some time...

**Review by svanharmelen — COMMENTED** [review]
Sorry for the late response @QuentinBrosse, but I needed to think about this one... I think that the impact of changing the ID type from `int` to `interface{}` could be very impactful. So I would like to suggest an alternative solution which makes the purpose of the fields my explicit.

What do you think about a solution like this?

**Comment by QuentinBrosse** [comment]
@svanharmelen don't worry it's okay.

Your suggestion is fine but, Gitlab supports other external issue trackers, not only Jira. Maybe we should rename the field `JiraID` to a more generic name? Something like `StringID`?

Keep in mind that the `id` field of the Gitlab API can be an `int` or a `string` ([the doc is available here](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-that-close-on-merge)).

What do you think about it? Thanks for your reply.

**Comment by svanharmelen** [comment]
What about this suggestion `ExternalID`? It's still not the perfect solution, but I think this will satisfy most use cases...

**Review by QuentinBrosse — COMMENTED** [review]
LGTM

**Pull request merged**
