### PR TITLE
Fixed fork-relation pid argument

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by svanharmelen** [comment]
Not sure what is fixed here? Why change this?

**Comment by mitar** [comment]
One could not pass project path string as pid argument like in all other API functions. So this unified these two functions to be the same as the rest of API functions in this package.

**Review by svanharmelen — APPROVED** [review]
I completely read this the wrong way 😅 LGTM! Thanks

**Comment by mitar** [comment]
:-)

Thanks for quick reviews!

**Pull request merged**
