### PR TITLE
pages domain verification

### PR DESCRIPTION
**Pull request by Jonarod**
Adding new fields to pages domain struct after new 2-step domain ownership verification.

### CODE REVIEW

**Comment by Lorac** [comment]
@svanharmelen Is there a "commit message" rules if so, I would suggest to change it to something more appropriate. 
```
Add missing pages domain verification fields.

Some description why they were missing...
```

**Comment by svanharmelen** [comment]
No, there are no commit message rules. And personally I don’t think we need one... 

But maybe we could add a few suggestions to a [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/),  think that should be more than sufficiant.

**Comment by zaquestion** [comment]
fwiw, I'm personally quite fond of 
```
[Issue-key] (context) what / topic statement

Why in body
```
Yeah though don't think it needs to be a rule and issue/PR templates seem like a great idea lot more  action in the repo lately in particular.

**Comment by Jonarod** [comment]
@svanharmelen check this [solved issue](https://gitlab.com/gitlab-com/support-forum/issues/3002#note_60334972). If you test the "create pages domain" API endpoint, you'll see these new fields, hence the new struct.

**Comment by svanharmelen** [comment]
Check... Thanks again @Jonarod! LGTM!

**Pull request merged**
