### PR TITLE
Align `/deploy_keys` API to get instance-wide deploy keys

### PR DESCRIPTION
**Pull request by timofurrer**
Apparently, the response here has changed from GitLab v13 to GitLab v14.

see https://docs.gitlab.com/ee/api/deploy_keys.html

We'd love to have this in the next release for the terraform provider, see:

* https://github.com/gitlabhq/terraform-provider-gitlab/issues/373

### CODE REVIEW

**Comment by timofurrer** [comment]
@svanharmelen would be nice to have this in the next release 🎉

**Review by svanharmelen — APPROVED** [review]
Cleaned things up just a little... Should be good like this.

**Comment by timofurrer** [comment]
@svanharmelen Could you please release this? Maybe also include #1407 so that we have a bunch of things for the terraform provider in one release ...

**Comment by svanharmelen** [comment]
Released `v0.59.0`

**Pull request merged**
