### PR TITLE
Fix: #973 Added Labels field to IssueCommentEvent.Issue

### PR DESCRIPTION
**Pull request by haardikdharma10**
This PR aims to solve #973.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@haardikdharma10 just for info, but the JSON file you updated is only used by tests and does not impact the code. So not sure if this is a complete solution for #973

**Comment by svanharmelen** [comment]
I'll merge this one, but it doesn't fix or change anything. I assume you realize that right?

**Comment by svanharmelen** [comment]
@haardikdharma10 can you confirm that you understand that this change doesn't actually change or fix anything?

**Comment by haardikdharma10** [comment]
@svanharmelen Yes I do, please merge it.

**Pull request merged**
