### PR TITLE
Add Merge Request Detailed Status

### LINKED ISSUE #1601: Merge Request Detailed Status
Is it possible to add detailed_merge_status to query all potential statuses?

https://docs.gitlab.com/ee/api/merge_requests.html#merge-status

### PR DESCRIPTION
**Pull request by VenuManikanta**
added detailed_merge_status field to MergeRequest struct and updated tests accordingly
Resolve #1601

### CODE REVIEW

**Review by svanharmelen — APPROVED** [review]
Looks good, thanks @VenuManikanta 👍🏻

**Comment by svanharmelen** [comment]
Ai, it seems `TestMilestonesService_GetMilestoneMergeRequests` still needs to be updated...

**Comment by VenuManikanta** [comment]
Can you approve the workflow? I have updated the test cases and tested them locally

**Comment by svanharmelen** [comment]
Thanks 👍🏻

**Pull request merged**
