### PR TITLE
A more flexible solution for configuring authentication

### PR DESCRIPTION
**Pull request by svanharmelen**

### CODE REVIEW

**Comment by svanharmelen** [comment]
Inspired by both #969, #970 (@firelizzard18) and #1026 (@RangerCD), would this be a good way forward?

Still in doubt if (for backwards compatibility) we should leave the old `NewClient` function in tact and replace only the others with a single new client function. Yet personally I prefer to refactor them all into one new function. Makes it pretty clean I think and uses a little bit of both suggested solutions.

**Comment by firelizzard18** [comment]
@svanharmelen This is definitely a step forward, but I would still prefer something that allows me to take control of the authentication process.

**Comment by RangerCD** [comment]
@svanharmelen This looks good enough to me :+1: .

**Comment by svanharmelen** [comment]
I think that by now we support all the tokens you tried to support using this PR. I understand it's a bit less flexible and might have a tiny bit of duplicate code, but for now I'm not really willing to make any big changes around this point so I will not be merging this PR...

**Pull request closed without merging**
