### PR TITLE
Add GenericPackagesServices (#1100)

### PR DESCRIPTION
**Pull request by neomantra**
This PR continues the work in #1101, rebasing it to master, updating its interface (returning download URL), and some real-world testing (fixed the URL endpoint and request type).

### CODE REVIEW

**Comment by matejvelikonja** [comment]
@svanharmelen  any chance for merging this?

**Comment by dewey** [comment]
Thanks for working on it @neomantra! Hope this gets merged soon to unblock the goreleaser fix.

**Comment by neomantra** [comment]
I just rebased this branch onto latest master and resolved the minor conflicts.

**Comment by svanharmelen** [comment]
I'll have a look at this one tomorrow!

**Review by svanharmelen — COMMENTED** [review]
I pushed a commit to tweak the PR and make it more inline with the rest of this package. I think the only thing that is still missing (which would make sense to add, but is not required), is adding support for the `select` option when publishing a package.

Please let me know what you think about the changes and if this will still work for you.

**Comment by neomantra** [comment]
Thanks for the review and improvements.  I'm adding `select` and am testing this end-to-end  with `goreleaser` patches.

**Comment by svanharmelen** [comment]
I again added a commit to complete the PR and I removed your last commit as I don't like to add and export custom logic, but only support calls that the Gitlab API supports.

Please confirm if this solution works for you so I can go ahead and merge it. Thanks!

**Comment by neomantra** [comment]
Thanks for the review and update.   It's pretty convenient to have that `GetGenericPackageURL` function as the end-user needs to know the URL structure, which `gitlab-go` already knows as it needs it too; they must also include a function like `pathEscape`.   I also note that the `select` result of `GenericPackagesFile.File.URL` is not the same URL as `GetGenericPackageURL` but some AWS S3 URL (at least for gitlab.com).  

But I also appreciate a purist approach to the library.  I tested the latest against an updated `goreleaser` and it works.  I also tested the `select` function and it works.  Thanks again for the attention to this issue.

**Comment by svanharmelen** [comment]
Hmm... Well OK then add your latest commit back so we can include that one after all...

**Comment by neomantra** [comment]
OK, I added it back.  I changed the verb from `Get` to `Format`... `FormatPackageURL` .. to prevent confusion with the common `Get*` Gitlab API operations and documented that it doesn't make an API call.  I'm fine with another verb, but changed it given your feedback.

**Comment by svanharmelen** [comment]
Nice, I can appreciate that one! Now if you can only swap the `PublishPackageFileOptions` and the `FormatPackageURL` method so that `PublishPackageFileOptions` is just above the method that uses it, I think we are good to go!

**Review by svanharmelen — APPROVED** [review]
Thanks for your patience with this one @neomantra 👍🏻

**Pull request merged**
