### PR TITLE
Added Confidential Issue Hook

### PR DESCRIPTION
**Pull request by jbguerraz**
Atdds the confidential issue hook field to the project and service structures

### CODE REVIEW

**Comment by svanharmelen** [comment]
@jbguerraz I don't see that field in the docs... Can you show me something that confirms this field is used/available? Thx!

**Comment by Lorac** [comment]
Maybe not in the doc, but it's in the source code at least

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/spec/factories/project_hooks.rb

**Comment by svanharmelen** [comment]
Check! Thanks for the confirmation @Lorac!

**Comment by jbguerraz** [comment]
My bad! this doesn't works :(

Gitlab is managing the confidential issues hooks in a _special_ way; at least those hooks are not exposed to the API but only available using the UI (so even a hook GET will not show the `confidential_issues_events` field).

Opened an issue : https://gitlab.com/gitlab-org/gitlab-ce/issues/43425

Meanwhile, that can be reverted.

**Comment by svanharmelen** [comment]
Reverted for now 👍 (#347)

**Comment by jbguerraz** [comment]
FYI: Some progress on https://gitlab.com/gitlab-org/gitlab-ce/issues/43425

**Comment by jbguerraz** [comment]
@svanharmelen https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/17370 it's merged! it's gonna be part of the next release, maybe we could apply that patch as anyway it won't hurts with current gitlab state  (it's just silently ignored now). What do you think ? :)

**Comment by svanharmelen** [comment]
Thanks for following up @jbguerraz! If you can recreate the PR, I will merge it again :wink:

**Comment by jbguerraz** [comment]
@svanharmelen done! see https://github.com/xanzy/go-gitlab/pull/352

**Pull request merged**
