### PR TITLE
add PerPage param to ListProjectOptions

### PR DESCRIPTION
**Pull request by Gnappuraz**
This option is missing in many calls I believe, and I especially need it here.

### CODE REVIEW

**Comment by zaquestion** [comment]
`PerPage` and `Page` are available on the [embedded](https://github.com/xanzy/go-gitlab/blob/master/projects.go#L182) ListOptions struct: 

Ref: [gitlab.go#237](https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L237)

**Comment by svanharmelen** [comment]
@Gnappuraz, @zaquestion is perfectly right... I will close this PR as the fields you are looking for are already added using the embedded `ListOptions` struct.

Feel free to open an issue if you have any additional issues or questions regarding this!

**Comment by Gnappuraz** [comment]
Thanks for pointing me to the right spot. Sorry I couldn't find it before.

**Comment by svanharmelen** [comment]
No problem at all! 👍

**Pull request closed without merging**
